version: "3"

services:
  docker-registry-cache:
    domainname: "${DOMAIN_NAME}"
    environment:
      MIRROR_SOURCE_INDEX: "https://index.docker.io"
      REGISTRY_PROXY_REMOTEURL: "https://registry-1.docker.io"
    hostname: "${HOST_NAME}"
    image: registry:2
    labels:
      traefik.domain: "${HOST_NAME}.${DOMAIN_NAME}"
      traefik.frontend.rule: "Host: docker-registry-cache.${HOST_NAME}.${DOMAIN_NAME}"
      traefik.port: "5000"
    restart: always
    volumes:
      - "registry:/var/lib/registry"

networks:
  default:
    external:
      name: "webhost"

volumes:
  registry:
