version: "3"

services:
  docker-registry-cache:
    domainname: "${DOMAIN_NAME}"
    environment:
      MIRROR_SOURCE_INDEX: "https://index.docker.io"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/${HOST_NAME}.${DOMAIN_NAME}.crt"
      REGISTRY_HTTP_TLS_KEY: "/certs/${HOST_NAME}.${DOMAIN_NAME}.key"
      REGISTRY_PROXY_REMOTEURL: "https://registry-1.docker.io"
    hostname: "${HOST_NAME}"
    image: registry:2
    ports:
      - "${HOST_IP}:5000:5000"
    restart: always
    volumes:
      - "./overlay/certs/:/certs/"
      - "./overlay/var/lib/registry/:/var/lib/registry/"
